### ISSUE TITLE
Potential issue with timing in multithreading environment

### ISSUE THREAD

**Issue by micahjsmith** [micahjsmith/stacklog#3]
* stacklog version: 1.1.0
* Python version: 3.11

### Description

Timing reported seems to be incorrect in some situations

### What I Did

```
2024-07-25 04:02:57,623 Running myfunction...
2024-07-25 04:03:10,177 Running myfunction...DONE in 1.31 s
```

It reports 1.31s but it actually took ~13s

**Comment by micahjsmith** [comment]
Reproduced in this stylized example

```
import time
import threading

def foo():
    elapsed = None

    def start():
        global elapsed
        elapsed = time.time()

    def end():
        global elapsed
        elapsed = time.time() - elapsed

    def print_():
        global elapsed
        print(elapsed)

    start()
    time.sleep(1)
    end()
    print_()


if __name__ == "__main__":
    threads = []
    for _ in range(10):
        threads.append(threading.Thread(target=foo))
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()
    print('done')
```

```
$ python test.py 
1.0017480850219727
1730141821.5548658
1.0017590522766113
1730141821.557236
1.0018329620361328
1.0018408298492432
1730141821.55726
1730141821.557271
1730141821.5572522
1.001849889755249
done
```

the `global` syntax was incorrect in version 1.x. the `nonlocal` syntax should have been used instead. in this stylized example, the identifier `elapsed` in `foo` scope is never accessed. the `global elapsed` declaration in inner scope creates a new single global variable that is shared by all functions. this was incorrectly done at https://github.com/micahjsmith/stacklog/blob/v1.1.0/stacklog/__init__.py#L250

this has been fixed in https://github.com/micahjsmith/stacklog/commit/1010a365040d31d90680e515484218b430286149#diff-b3a0d340a039b43b4a15ba8fd43be822f208476f4cf370799a228c4d011d6c1a and is in the 2.x release series

**Comment by andyyoon2** [comment]
Great find, I appreciate the investigation! Thanks!!
